### ISSUE TITLE
can not be used when making a PIE object; recompile with -fPIE

### ISSUE THREAD

**Issue by Tsunaou** [memgraph/mgclient#44] opened 2022-11-07 12:17 UTC
- CentOS 7
- CMake 3.20.2
- OpenSSL 1.1.1k
- GCC 8.5.0

I build this project in CentOS 7 and I want to take use of it in Rust. 
However, it reported this error that I can not handle. I am not familiar with cmake so it is hard to solve it.

```bash
  = note: /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgclient.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgmessage.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgsession.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgsession-decoder.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgsession-encoder.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgtransport.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgvalue.c.o): relocation R_X86_64_32 against symbol `mg_system_allocator' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgsocket.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libmgclient.a(mgallocator.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
          collect2: error: ld returned 1 exit status
```

I try to add "-no-pie" option but it did not help at all.
```txt
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIE -no-pie")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIE -no-pie")

# Set default build type to 'Release'
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release")
endif()
message(STATUS "CMake build type: ${CMAKE_BUILD_TYPE}")
```

**Comment by antaljanosbenjamin** [comment] 2022-11-07 13:23
Hi @Tsunaou,

First of all, thanks for reaching out. Could you please provide a bit more context when do you see this error? If you could provide a minimal reproducible example (even a dummy example is fine, where this error occurs), that would help us provide better help.

First of all, I am a bit confused why do you specify both `-fPIE` and `-no-pie`, as `-fPIE` turns on position independent code generation, while `-no-pie` turns it off. I might not be aware of something, so please correct me if I am wrong.

From the error message I saw I assume that you are trying to link `mgclient-static` to a shared library or executable that requires position independent code and it fails because the library is **not compiled** with -fPIC. Instead of changing the `CMAKE_C_FLAGS` or `CMAKE_CXX_FLAGS`, could you please try to turn on position independent code generation by `set(CMAKE_POSITION_INDEPENDENT_CODE ON)`? I think it should be fine right above the `# Set default build type to 'Release'` line.

**Comment by antaljanosbenjamin** [comment] 2022-11-07 13:57
Sorry, I was wrong here:
> could you please try to turn on position independent code generation by set(CMAKE_POSITION_INDEPENDENT_CODE ON)?

`CMAKE_POSITION_INDEPENDENT_CODE` is used only when you generate CMake: `cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON`. In CMakeFiles you have to set `set(POSITION_INDEPENDENT_CODE ON)` (note the lack of `CMAKE_` prefix.

**Comment by Tsunaou** [comment] 2022-11-07 14:02
@antaljanosbenjamin 
Thank you very much for your guidance. 
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)` work well and I can build successfully.

Your assumption is correct. I am trying to link `mgclient-static` to a rust program requiring position-independent code. The project is in https://github.com/amnore/dbcop, which is a database runner. 

Actually, it is the first time that I met position-independent code. Both `-fPIE` and `-no-pie` are options that I copied from StackOverflow or other forums I searched in google. Maybe I should learn more about gcc and make. Thanks for your help again.

**Comment by Tsunaou** [comment] 2022-11-07 14:06
@antaljanosbenjamin 
It is amazing that `CMAKE_POSITION_INDEPENDENT_CODE` works well also. CMake is too wonderful.

**Comment by antaljanosbenjamin** [comment] 2022-11-07 14:13
Is there anything else I can help you with, or can we close this issue?

**Comment by Tsunaou** [comment] 2022-11-07 14:15
Nothing else. This issue could be closed gracefully. Thanks.

**Comment by antaljanosbenjamin** [comment] 2022-11-07 14:23
Your welcome! If you need any more help, feel free reach out again!

**Closed by antaljanosbenjamin** 2022-11-07 14:23 UTC

**Comment by gitbuda** [comment] 2022-11-07 14:25
@Tsunaou since you mentioned Rust, maybe the Rust client using `mgclient` -> https://github.com/memgraph/rsmgclient is interesting? 🤔
